spring:
  application:
    name: userservice
  datasource:
    url: jdbc:h2:mem:userervicedb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db-templates/schema.sql
      data-locations: classpath:db-templates/data.sql
  h2:
    console:
      enabled: true
  logging:
    level:
      org:
        hibernate:
          sql: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
server:
  port: 8083
  servlet:
    context-path: /userapi/v1